php=set()
java=set()
python=set()
l=int(input("enter the limit for php"))
for i in range(l):
    a=str(input("enter the names in php"))
    php.add(a)
print()
l=int(input("enter the limit for java"))
for i in range(l):
    a=str(input("enter the names in java"))
    java.add(a)
print()
l=int(input("enter the limit for python"))
for i in range(l):
    a=str(input("enter the names in python"))
    python.add(a)
print()
print("php")
print(php)
print("java")
print(java)
print("python")
print(python)
print("students in 3sub")
b=php.intersection(java)
print( b.intersection(python))
print("students in 1sub")
c=php.symmetric_difference(java)
d=php.symmetric_difference(python)
print(c.symmetric_difference(d))
